---
abstract: "We are the Bangalore Perl Mongers, find us at all the places listed below!\nIf you are in or around Bangalore near the first week of a month, do drop by for our meetups listed \nat bangalore.pm.org"
author:
  - 'Shantanu Bhadoria <shantanu at cpan dott org>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930001'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PerlMongers-Bangalore
no_index:
  directory:
    - xt
requires:
  Acme::CPANAuthors: 0
  Acme::CPANAuthors::Register: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=PerlMongers-Bangalore
  homepage: https://github.com/shantanubhadoria/PerlMongers--Bangalore
  license: http://dev.perl.org/licenses/
  repository: git://github.com/shantanubhadoria/perlmongers-bangalore.git
version: 0.02
x_authority: cpan:SHANTANU
